require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'Geek_House' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'ReactNativeAdsFacebook', :path => '../node_modules/react-native-fbads'

  pod 'CodePush', :path => '../node_modules/react-native-code-push'

  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  pod 'WatermelonDB', :path => '../node_modules/@nozbe/watermelondb'

  target 'Geek_HouseTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'Geek_House-tvOS' do
  # Pods for Geek_House-tvOS

  target 'Geek_House-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
